name: Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        push: true
        platforms: linux/amd64
        tags: ghcr.io/${{ github.actor }}/fona-client-final:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          LOWERCASE_ACTOR=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          docker login ghcr.io -u ${LOWERCASE_ACTOR} --password ${{ secrets.GITHUB_TOKEN }}
          docker pull ghcr.io/${LOWERCASE_ACTOR}/fona-client-final:latest
          docker stop fona-client-final || true
          docker rm fona-client-final || true
          docker run -d --name fona-client-final -p 8080:80 ghcr.io/${LOWERCASE_ACTOR}/fona-client-final:latest
