name: Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u gnlimerence --password-stdin

    - name: Build and Push Docker Image
      working-directory: frontend
      run: |
        docker build --platform linux/amd64 -t ghcr.io/gnlimerence/fona-client-final:latest .
        docker push ghcr.io/gnlimerence/fona-client-final:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          docker login ghcr.io -u gnlimerence --password ${{ secrets.GITHUB_TOKEN }}
          docker pull ghcr.io/gnlimerence/fona-client-final:latest
          docker stop fona-client-final || true
          docker rm fona-client-final || true
          docker run -d --name fona-client-final -p 8080:80 ghcr.io/gnlimerence/fona-client-final:latest
